import express from 'express'
import cors from 'cors'
import cookieParser from 'cookie-parser'

const app = express()

app.use(cors({                  // used as middleware
    origin: process.env.CORS_ORIGIN,
    credentials:true,
}))

app.use(express.json({          //used to retrive the data in the forms in form of json
    limit:'20kb'
}))

app.use(express.urlencoded({    //used for reading the encoded url generated by the browser
    extended:true,
    limit:'20kb',
}))

app.use(cookieParser())

//routes imports

import userRouter from './routes/user.routes.js'

// routes declaration
// We are using use function instead of get or any other function because we segregated the routes in the route folder
// so in order to use the routes we introduce 'middleware' in between(also this is the syntax to follow)

app.use('/api/v1/users',userRouter)

// where will the route go http://localhost:8000/api/v1/users/register

export {app}