import express from 'express'
import cors from 'cors'
import cookieParser from 'cookie-parser'

const app = express()

app.use(cors({                  // used as middleware
    origin: process.env.CORS_ORIGIN,
    credentials:true,
}))

app.use(express.json({          //used to retrive the data in the forms in form of json
    limit:'20kb'
}))

app.use(express.urlencoded({    //used for reading the encoded url generated by the browser
    extended:true,
    limit:'20kb',
}))

app.use(cookieParser())

export default app